# This is a basic workflow to help you get started with Actions

name: java

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
#     if: github.event == 'push'
    strategy:
      matrix:
        java: ['8', '11']
    name: Java ${{ matrix.java }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - run: |
          gradle jar
